name: shellcheck

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install shellcheck
        # from https://github.com/koalaman/shellcheck#user-content-installing
        run: sudo apt install -y shellcheck

      - name: using shellcheck
        run:  shellcheck pii_redactor.sh
